name: CI Pipeline

on:
  push:
    branches: [main]
  #pull_request:
  #  branches: [main]

jobs:
  # =========================
  # 🔹 Backend - NestJS
  # =========================
  backend:
    name: Backend (NestJS)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: nestjs-cicd-backend

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🧹 Run ESLint
        run: npm run lint

      - name: 🧪 Run Tests
        run: npm run test

      - name: 🏗 Build App
        run: npm run build

  # =========================
  # 🔹 Frontend - React
  # =========================
  frontend:
    name: Frontend (React)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: reactjs-cicd-frontend

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install Dependencies
        run: npm install

      # skip tests temporarily
      - name: 🧪 Run Tests
        run: npm test

      - name: 🏗 Build App
        run: npm run build
